# Generated by Django 2.1 on 2018-12-18 21:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_auto_20181218_0351'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 21, 37, 49, 126055, tzinfo=utc), verbose_name=datetime.datetime(2018, 12, 18, 21, 37, 6, 957459, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todoitem',
            name='complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
