# Generated by Django 2.1 on 2018-12-18 21:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0004_auto_20181218_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 18, 21, 57, 40, 441250, tzinfo=utc)),
        ),
    ]
