# Generated by Django 2.1 on 2018-12-19 02:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_auto_20181218_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='complete_item',
            new_name='complete',
        ),
        migrations.AddField(
            model_name='todoitem',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 19, 2, 22, 2, 713243, tzinfo=utc)),
        ),
    ]
